project:
  type: book
output-dir: _book
book:
  title: "Outils de recherche en sciences sociales numériques"
  author: "CLESSN — Sous la direction de A. Bibeau-Gagnon, A. Cloutier, Y. Dufresne"
  date: today
  chapters:
    - index.qmd
    - chapitre_1.qmd
    - chapitre_2.qmd
    - chapitre_3.qmd
    - chapitre_4.qmd
    - chapitre_5.qmd
    - chapitre_6.qmd
    - chapitre_7.qmd
    - chapitre_8.qmd
    - chapitre_9.qmd
  appendices:
    - annexe_a.qmd
    - annexe_b.qmd
    - references.qmd
bibliography: livre-outils.bib
csl: https://www.zotero.org/styles/apa
lang: fr
format:
  pdf:
    classoption: [oneside]        # mêmes marges à gauche/droite partout
    geometry: margin=30mm         # ajuste à ton goût
    include-in-header:
      - text: |
          \usepackage{setspace}
          \usepackage{csquotes}
          \newcommand{\R}{\textsf{R}}

editor: source
