project:
  type: book
  output-dir: book

book:
  title: "Outils de recherche en sciences sociales num√©rique"
  author: "CLESSN"
  date: "8/05/2023"
  chapters:
    - index.qmd
    - chapitre_1.qmd
    - chapitre_2.qmd
    - chapitre_3.qmd
    - chapitre_4.qmd
    - chapitre_5.qmd
    - chapitre_6.qmd
    - chapitre_7.qmd
    - chapitre_8.qmd
    - chapitre_9.qmd
    - chapitre10.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt

editor: visual

