project:
  type: book
output-dir: _book
book:
  title: "Outils de recherche en sciences sociales numériques"
  author: "Chaire de leadership en enseignement des sciences sociales numériques (CLESSN)"
  date: today
  chapters:
    - index.qmd
    - chapitre_1.qmd
    - chapitre_2.qmd
    - chapitre_3.qmd
    - chapitre_4.qmd
    - chapitre_5.qmd
    - chapitre_6.qmd
    - chapitre_7.qmd
    - chapitre_8.qmd
    - chapitre_9.qmd
    - conclusion.qmd
    - annexe_1.qmd
    - references.qmd
bibliography: livre-outils.bib
csl: https://www.zotero.org/styles/apa
lang: fr
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    code-fold: false
    code-tools: false
  pdf:
    classoption: [oneside]        # mêmes marges à gauche/droite partout
    geometry: margin=30mm         # ajuste à ton goût
    include-in-header:
      - text: |
          \usepackage{setspace}
          \usepackage{csquotes}
  docx:
    toc: true
    number-sections: true
    highlight-style: github
    reference-doc: reference-template.docx

editor: source
