project:
  type: book
  output-dir: _SharedFolder_livre-outils

book:
  title: "Introduction aux sciences sociales num√©rique"
  author: "CLESSN"
  date: "7/15/2023"
  chapters:
    - index.qmd
    - introduction.qmd
    - chapitre_1.qmd
    - chapitre_2.qmd
    - chapitre_3.qmd
    - chapitre_4.qmd
    - chapitre_5.qmd
    - chapitre_6.qmd
    - chapitre_7.qmd
    - chapitre_8.qmd
    - chapitre_9.qmd
    - references.qmd

bibliography: _SharedFolder_livre-outils/references.bib

format:
  pdf:
    documentclass: scrreprt

editor: visual

